#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "518448b608034488a693b68dcdf89900" }
]

[assets]
directory = "./public"
